/**
 * 主题预设
 * ============================================================
 * 一套 CSS 不动，只换变量值就能从"新拟态"切到"扁平"或"玻璃"：
 *   · 新拟态 —— --surface 与 --bg 同色，靠 --sh-dark / --sh-light 双向阴影塑形
 *   · 扁平   —— --sh-* 调到与底色几乎同色（阴影隐形），改由 --border 描边
 *   · 玻璃   —— --surface 半透明 + --blur 打开毛玻璃
 * 所以每套主题只需定义下面这组变量。
 *
 * base 字段很关键：它告诉插件适配器"面板现在是深色还是浅色"，
 * 用于判断第三方插件需不需要反转（见 theme-normalizer.js）。
 *
 * 排列与书写约定（便于逐行比对，新增主题时照抄即可）：
 *   1. 先按风格分组（新拟态 → 扁平 → 玻璃），组内深色在前、浅色在后
 *   2. 变量按 基底 → 塑形 → 文本 → 主色 → 状态色 → 风格 → 圆角 的顺序写
 *   3. 派生量（--hairline / --mask / --scroll-thumb / --badge-fg / --accent-glow）
 *      由 theme-manager 统一算，主题里不要写
 *   4. 圆角只在需要偏离默认值的风格里写（扁平 / 玻璃），且必须四个一起写 ——
 *      只写一半会让上一主题的内联值残留（见 theme-manager 的清空逻辑）
 *   5. 文本与点缀色的对比度有下限：正文 ≥ 4.5、次级 ≥ 3，
 *      改色值后请跑 `npm run test:theme`
 */

export const THEME_VARS = [
  // 基底：底色 / 背景渐变 / 卡片面 / 凹陷面 / 浮起一档的面
  '--bg', '--bg-image', '--surface', '--surface-sunk',
  // 塑形：右下暗、左上亮
  '--sh-dark', '--sh-light',
  // 文本：正文 / 次正文 / 次级 / 最弱
  '--text', '--text-dim', '--text-mute',
  // 环境色（原「主题色」）：与强调色并列的第二个可调主色，只作次要点缀。
  // 状态色（--ok/--running/--warn/--danger）语义固定，不随它变化。
  '--accent', '--env-color', '--accent-glow',
  // 状态色：与装饰色（accent / accent-2）分离，不参与主题色微调。
  // 否则用户把主题色设成红色，就会出现"红色的成功提示"。
  '--ok', '--running', '--warn', '--danger',
  '--surface-raised', '--text-soft',
  '--border', '--blur', '--hairline', '--mask',
  '--scroll-thumb', '--badge-fg',
  // 圆角也是形状语言的一部分：新拟态的大圆角是"软"的一部分，
  // 扁平/Linear 风需要更硬朗的值。未定义的主题回退 CSS 默认值。
  '--r-xl', '--r-lg', '--r-md', '--r-sm',
];

/**
 * style → 中文名。
 *
 * 主题卡片右上角的小角标用它，让"同样是深色"的几套能一眼分出新拟态 / 扁平 / 玻璃。
 * 放在主题数据里而不是各 UI 组件里，是为了让选择器与设置页永远显示同一套叫法。
 */
export const STYLE_LABELS = { neumorph: '新拟态', flat: '扁平', glass: '玻璃' };

/** 取风格的中文名；未知风格（如自定义主题没写 style）返回空串，卡片上就不显示角标 */
export function styleLabel(style) {
  return STYLE_LABELS[style] || '';
}

export const PRESET_THEMES = [
  /* ---------------- 新拟态 · 深色 ---------------- */
  {
    id: 'neumorph-dark',
    name: '深色新拟态',
    desc: '灰蓝底 · 元素与背景同色，靠双向阴影塑形',
    base: 'dark',
    style: 'neumorph',
    vars: {
      '--bg': '#2b2f36',
      '--surface': '#2b2f36',
      '--surface-sunk': '#282c33',
      '--surface-raised': '#373c45',
      '--sh-dark': '#1d2027',
      '--sh-light': '#383e49',
      '--text': '#d9dee8',
      '--text-soft': '#bac0cc',
      '--text-dim': '#9198a7',
      '--text-mute': '#737c8a',
      '--accent': '#5b8cff',
      '--env-color': '#48e0c0',
      '--ok': '#22c55e',
      '--running': '#4c8dff',
      '--warn': '#f59e0b',
      '--danger': '#ef4444',
      '--border': 'transparent',
      '--blur': '0px',
    },
  },
  {
    id: 'midnight',
    name: '午夜蓝',
    desc: '深蓝调 · 沉稳耐看，适合长时间盯屏',
    base: 'dark',
    style: 'neumorph',
    vars: {
      '--bg': '#232838',
      '--surface': '#232838',
      '--surface-sunk': '#1f2432',
      '--surface-raised': '#2d3348',
      '--sh-dark': '#171b28',
      '--sh-light': '#2f3548',
      '--text': '#cdd4e6',
      '--text-soft': '#aeb6cc',
      '--text-dim': '#8791ac',
      '--text-mute': '#697497',
      '--accent': '#6f9cff',
      '--env-color': '#5ad3c8',
      '--ok': '#22c55e',
      '--running': '#4c8dff',
      '--warn': '#f59e0b',
      '--danger': '#ef4444',
      '--border': 'transparent',
      '--blur': '0px',
    },
  },
  {
    id: 'graphite',
    name: '石墨灰',
    desc: '中性深灰 · 不抢戏，长时间盯屏最舒服',
    base: 'dark',
    style: 'neumorph',
    vars: {
      '--bg': '#303236',
      '--surface': '#303236',
      '--surface-sunk': '#2c2e31',
      '--surface-raised': '#3d4045',
      '--sh-dark': '#222427',
      '--sh-light': '#404347',
      '--text': '#e3e5e8',
      '--text-soft': '#c6c9ce',
      '--text-dim': '#9ba0a8',
      '--text-mute': '#7a7f88',
      '--accent': '#7c9fff',
      '--env-color': '#6fd3a8',
      '--ok': '#22c55e',
      '--running': '#4c8dff',
      '--warn': '#f59e0b',
      '--danger': '#ef4444',
      '--border': 'transparent',
      '--blur': '0px',
    },
  },
  {
    id: 'celadon',
    name: '青瓷',
    desc: '墨绿底 · 青瓷釉色，沉静有质感',
    base: 'dark',
    style: 'neumorph',
    vars: {
      '--bg': '#24302c',
      '--surface': '#24302c',
      '--surface-sunk': '#202b27',
      '--surface-raised': '#2e3d38',
      '--sh-dark': '#18211e',
      '--sh-light': '#314039',
      '--text': '#d8e5df',
      '--text-soft': '#b9cbc3',
      '--text-dim': '#8ba398',
      '--text-mute': '#677f72',
      '--accent': '#6fcf97',
      '--env-color': '#a8d8b9',
      '--ok': '#22c55e',
      '--running': '#4c8dff',
      '--warn': '#f59e0b',
      '--danger': '#ef4444',
      '--border': 'transparent',
      '--blur': '0px',
    },
  },
  {
    id: 'amber-dusk',
    name: '暮橙',
    desc: '深褐底 · 琥珀点缀，暖意十足',
    base: 'dark',
    style: 'neumorph',
    vars: {
      '--bg': '#2e2723',
      '--surface': '#2e2723',
      '--surface-sunk': '#2a241f',
      '--surface-raised': '#3b322d',
      '--sh-dark': '#1f1a17',
      '--sh-light': '#3d342e',
      '--text': '#ece2d8',
      '--text-soft': '#d2c6ba',
      '--text-dim': '#ab9c8d',
      '--text-mute': '#817367',
      '--accent': '#ffa94d',
      '--env-color': '#ffd8a8',
      '--ok': '#22c55e',
      '--running': '#4c8dff',
      '--warn': '#f59e0b',
      '--danger': '#ef4444',
      '--border': 'transparent',
      '--blur': '0px',
    },
  },
  {
    id: 'violet-dusk',
    name: '紫暮',
    desc: '深紫底 · 品红点缀，优雅神秘',
    base: 'dark',
    style: 'neumorph',
    vars: {
      '--bg': '#2b2740',
      '--surface': '#2b2740',
      '--surface-sunk': '#272335',
      '--surface-raised': '#373252',
      '--sh-dark': '#1d1a2b',
      '--sh-light': '#3a3557',
      '--text': '#e2ddf0',
      '--text-soft': '#c5bfda',
      '--text-dim': '#9a92b8',
      '--text-mute': '#797296',
      '--accent': '#b48cff',
      '--env-color': '#ff8fd0',
      '--ok': '#22c55e',
      '--running': '#4c8dff',
      '--warn': '#f59e0b',
      '--danger': '#ef4444',
      '--border': 'transparent',
      '--blur': '0px',
    },
  },
  {
    id: 'carbon-blue',
    name: '碳晶蓝',
    desc: '冷蓝调 · 编辑器风格，代码与数据友好',
    base: 'dark',
    style: 'neumorph',
    vars: {
      '--bg': '#1f2430',
      '--surface': '#1f2430',
      '--surface-sunk': '#1b202a',
      '--surface-raised': '#282e3d',
      '--sh-dark': '#141821',
      '--sh-light': '#2b3242',
      '--text': '#d4dae6',
      '--text-soft': '#b4bdce',
      '--text-dim': '#8492ab',
      '--text-mute': '#65728b',
      '--accent': '#4d9de0',
      '--env-color': '#56d4c4',
      '--ok': '#22c55e',
      '--running': '#4c8dff',
      '--warn': '#f59e0b',
      '--danger': '#ef4444',
      '--border': 'transparent',
      '--blur': '0px',
    },
  },
  {
    id: 'rose-noir',
    name: '玫瑰黑金',
    desc: '近黑底 · 香槟金配玫瑰，低调奢华',
    base: 'dark',
    style: 'neumorph',
    vars: {
      '--bg': '#1c1618',
      '--surface': '#1c1618',
      '--surface-sunk': '#161113',
      '--surface-raised': '#433c3e',
      '--sh-dark': '#120d0f',
      '--sh-light': '#2e2529',
      '--text': '#f0e4e6',
      '--text-soft': '#d6c7ca',
      '--text-dim': '#b09ba0',
      '--text-mute': '#7d6a70',
      '--accent': '#d4a574',
      '--env-color': '#c97b84',
      '--ok': '#22c55e',
      '--running': '#4c8dff',
      '--warn': '#f59e0b',
      '--danger': '#ef4444',
      '--border': 'transparent',
      '--blur': '0px',
    },
  },
  {
    id: 'ocean-deep',
    name: '深海',
    desc: '深蓝绿 · 天青点缀，通透清凉',
    base: 'dark',
    style: 'neumorph',
    vars: {
      '--bg': '#16262e',
      '--surface': '#16262e',
      '--surface-sunk': '#132227',
      '--surface-raised': '#1c313b',
      '--sh-dark': '#0f1a20',
      '--sh-light': '#1f343d',
      '--text': '#d5e6ec',
      '--text-soft': '#b5cbd4',
      '--text-dim': '#84a3b0',
      '--text-mute': '#5b7784',
      '--accent': '#38bdf8',
      '--env-color': '#5eead4',
      '--ok': '#22c55e',
      '--running': '#4c8dff',
      '--warn': '#f59e0b',
      '--danger': '#ef4444',
      '--border': 'transparent',
      '--blur': '0px',
    },
  },

  /* ---------------- 新拟态 · 浅色 ---------------- */
  {
    id: 'neumorph-light',
    name: '浅色新拟态',
    desc: '米白底 · 同样的立体感，明亮通透',
    base: 'light',
    style: 'neumorph',
    vars: {
      '--bg': '#e6e9ef',
      '--surface': '#e6e9ef',
      '--surface-sunk': '#dfe2e9',
      '--surface-raised': '#f4f5f8',
      '--sh-dark': '#c3c7d0',
      '--sh-light': '#f7f9fc',
      '--text': '#3a4050',
      '--text-soft': '#4d5464',
      '--text-dim': '#616778',
      '--text-mute': '#798297',
      '--accent': '#3b6fe0',
      '--env-color': '#10927a',
      '--ok': '#1a9446',
      '--running': '#437de1',
      '--warn': '#b17208',
      '--danger': '#e54141',
      '--border': 'transparent',
      '--blur': '0px',
    },
  },
  {
    id: 'paper',
    name: '宣纸',
    desc: '暖白纸感 · 朱砂点缀，久看不累',
    base: 'light',
    style: 'neumorph',
    vars: {
      '--bg': '#f0ece4',
      '--surface': '#f0ece4',
      '--surface-sunk': '#e7e2d8',
      '--surface-raised': '#f8f6f3',
      '--sh-dark': '#d4cfc4',
      '--sh-light': '#faf8f3',
      '--text': '#3d3830',
      '--text-soft': '#514b42',
      '--text-dim': '#6e675c',
      '--text-mute': '#8b8374',
      '--accent': '#b8694d',
      '--env-color': '#6b8e5a',
      '--ok': '#1a9446',
      '--running': '#4480e6',
      '--warn': '#b17208',
      '--danger': '#ef4444',
      '--border': 'transparent',
      '--blur': '0px',
    },
  },
  {
    id: 'mint-morning',
    name: '薄荷晨光',
    desc: '薄荷绿底 · 清爽明亮，不刺眼',
    base: 'light',
    style: 'neumorph',
    vars: {
      '--bg': '#e8f0ec',
      '--surface': '#e8f0ec',
      '--surface-sunk': '#dfe9e3',
      '--surface-raised': '#f5f8f6',
      '--sh-dark': '#c8d6cf',
      '--sh-light': '#f5faf8',
      '--text': '#2f4038',
      '--text-soft': '#44574e',
      '--text-dim': '#5b6f65',
      '--text-mute': '#738a7d',
      '--accent': '#1f8f6b',
      '--env-color': '#429474',
      '--ok': '#1a9446',
      '--running': '#4480e6',
      '--warn': '#b87708',
      '--danger': '#ef4444',
      '--border': 'transparent',
      '--blur': '0px',
    },
  },
  {
    id: 'sakura',
    name: '樱花',
    desc: '淡粉樱色 · 柔和温润',
    base: 'light',
    style: 'neumorph',
    vars: {
      '--bg': '#f5ebee',
      '--surface': '#f5ebee',
      '--surface-sunk': '#ede1e6',
      '--surface-raised': '#faf6f7',
      '--sh-dark': '#ddccd2',
      '--sh-light': '#fbf6f7',
      '--text': '#4a3238',
      '--text-soft': '#5e464d',
      '--text-dim': '#7c646b',
      '--text-mute': '#987e87',
      '--accent': '#d63a68',
      '--env-color': '#e64c7a',
      '--ok': '#1a9446',
      '--running': '#4480e6',
      '--warn': '#b87708',
      '--danger': '#ef4444',
      '--border': 'transparent',
      '--blur': '0px',
    },
  },
  {
    id: 'sandstone',
    name: '砂岩',
    desc: '大地色系 · 暖灰里带一点陶土',
    base: 'light',
    style: 'neumorph',
    vars: {
      '--bg': '#e9e4dc',
      '--surface': '#e9e4dc',
      '--surface-sunk': '#e0dad0',
      '--surface-raised': '#f5f3ef',
      '--sh-dark': '#cbc4b8',
      '--sh-light': '#f6f3ee',
      '--text': '#403a32',
      '--text-soft': '#544d44',
      '--text-dim': '#6b6458',
      '--text-mute': '#887d6b',
      '--accent': '#b0601f',
      '--env-color': '#6b865b',
      '--ok': '#199145',
      '--running': '#437de1',
      '--warn': '#aa6d08',
      '--danger': '#e54141',
      '--border': 'transparent',
      '--blur': '0px',
    },
  },

  /* ---------------- 扁平 ---------------- */
  {
    id: 'oled-flat',
    name: '纯黑扁平',
    desc: 'OLED 纯黑 · 无阴影，靠描边分层',
    base: 'dark',
    style: 'flat',
    vars: {
      '--bg': '#000000',
      '--surface': '#141416',
      '--surface-sunk': '#0c0c0e',
      '--surface-raised': '#3a3a3c',
      '--sh-dark': '#08080a',
      '--sh-light': '#0e0e10',
      '--text': '#e8e8ec',
      '--text-soft': '#c6c6cd',
      '--text-dim': '#94949e',
      '--text-mute': '#65656f',
      '--accent': '#7c8cff',
      '--env-color': '#3ddc97',
      '--ok': '#22c55e',
      '--running': '#4c8dff',
      '--warn': '#f59e0b',
      '--danger': '#ef4444',
      '--border': 'rgba(255,255,255,.09)',
      '--blur': '0px',
      '--r-xl': '12px',
      '--r-lg': '10px',
      '--r-md': '8px',
      '--r-sm': '5px',
    },
  },
  {
    id: 'neon-dark',
    name: '霓虹暗夜',
    desc: '品红配电光青 · 高饱和，科技感强',
    base: 'dark',
    style: 'flat',
    vars: {
      '--bg': '#12121c',
      '--surface': '#1b1b2b',
      '--surface-sunk': '#0e0e16',
      '--surface-raised': '#414153',
      '--sh-dark': '#0c0c14',
      '--sh-light': '#23233a',
      '--text': '#eae6ff',
      '--text-soft': '#cbc5e7',
      '--text-dim': '#9d94c4',
      '--text-mute': '#6d6692',
      '--accent': '#ff2e97',
      '--env-color': '#00e5ff',
      '--ok': '#22c55e',
      '--running': '#4c8dff',
      '--warn': '#f59e0b',
      '--danger': '#ef4444',
      '--border': 'rgba(255,46,151,.16)',
      '--blur': '0px',
      '--r-xl': '12px',
      '--r-lg': '10px',
      '--r-md': '8px',
      '--r-sm': '5px',
    },
  },
  {
    id: 'terminal',
    name: '终端绿',
    desc: 'CRT 荧光绿 · 复古极客味',
    base: 'dark',
    style: 'flat',
    vars: {
      '--bg': '#0d120e',
      '--surface': '#131a15',
      '--surface-sunk': '#090d0a',
      '--surface-raised': '#39403b',
      '--sh-dark': '#070a08',
      '--sh-light': '#161d18',
      '--text': '#6ee78f',
      '--text-soft': '#60ca7d',
      '--text-dim': '#4a9e63',
      '--text-mute': '#37754a',
      '--accent': '#8affc1',
      '--env-color': '#ffd166',
      '--ok': '#22c55e',
      '--running': '#4c8dff',
      '--warn': '#f59e0b',
      '--danger': '#ef4444',
      '--border': 'rgba(110,231,143,.14)',
      '--blur': '0px',
      '--r-xl': '12px',
      '--r-lg': '10px',
      '--r-md': '8px',
      '--r-sm': '5px',
    },
  },
  {
    id: 'cyberpunk',
    name: '赛博朋克',
    desc: '霓虹黄配电光青 · 最高对比度',
    base: 'dark',
    style: 'flat',
    vars: {
      '--bg': '#0f0f1a',
      '--surface': '#171728',
      '--surface-sunk': '#0a0a12',
      '--surface-raised': '#3d3d50',
      '--sh-dark': '#08080f',
      '--sh-light': '#1f1f36',
      '--text': '#f5f0ff',
      '--text-soft': '#d6ceee',
      '--text-dim': '#a89bd4',
      '--text-mute': '#6f6599',
      '--accent': '#f7ff3c',
      '--env-color': '#00fff0',
      '--ok': '#22c55e',
      '--running': '#4c8dff',
      '--warn': '#f59e0b',
      '--danger': '#ef4444',
      '--border': 'rgba(247,255,60,.18)',
      '--blur': '0px',
      '--r-xl': '12px',
      '--r-lg': '10px',
      '--r-md': '8px',
      '--r-sm': '5px',
    },
  },
  {
    id: 'minimal-white',
    name: '极简白',
    desc: '纯白底 · 细描边，接近文档工具观感',
    base: 'light',
    style: 'flat',
    vars: {
      '--bg': '#ffffff',
      '--surface': '#fbfbfc',
      '--surface-sunk': '#f4f4f6',
      '--surface-raised': '#fefeff',
      '--sh-dark': '#ececef',
      '--sh-light': '#f7f7f8',
      '--text': '#2d2d31',
      '--text-soft': '#434349',
      '--text-dim': '#65656e',
      '--text-mute': '#8d8d96',
      '--accent': '#2f6fed',
      '--env-color': '#1da178',
      '--ok': '#1b9d4b',
      '--running': '#4987f5',
      '--warn': '#c07c09',
      '--danger': '#ef4444',
      '--border': 'rgba(0,0,0,.08)',
      '--blur': '0px',
      '--r-xl': '12px',
      '--r-lg': '10px',
      '--r-md': '8px',
      '--r-sm': '5px',
    },
  },

  /* ---------------- 玻璃 ---------------- */
  {
    id: 'glass-dark',
    name: '玻璃拟态',
    desc: '半透明毛玻璃 · 背景带极光渐变',
    base: 'dark',
    style: 'glass',
    vars: {
      '--bg': '#1b1f2b',
      '--bg-image': 'radial-gradient(1200px 600px at 12% -10%, #2d3a5c 0%, transparent 60%), radial-gradient(900px 500px at 110% 110%, #4a2a55 0%, transparent 55%)',
      '--surface': 'rgba(255,255,255,.07)',
      '--surface-sunk': 'rgba(0,0,0,.22)',
      '--surface-raised': 'rgba(255,255,255,0.16)',
      '--sh-dark': 'rgba(0,0,0,.34)',
      '--sh-light': 'rgba(255,255,255,.07)',
      '--text': '#eef1f8',
      '--text-soft': '#d2d7e3',
      '--text-dim': '#a8b0c4',
      '--text-mute': '#767e94',
      '--accent': '#7aa2ff',
      '--env-color': '#5fe3d0',
      '--ok': '#22c55e',
      '--running': '#4c8dff',
      '--warn': '#f59e0b',
      '--danger': '#ef4444',
      '--border': 'rgba(255,255,255,.12)',
      '--blur': '14px',
      '--r-xl': '18px',
      '--r-lg': '14px',
      '--r-md': '11px',
      '--r-sm': '7px',
    },
  },
  {
    id: 'glass-light',
    name: '浅色玻璃',
    desc: '白底毛玻璃 · 淡蓝粉光晕',
    base: 'light',
    style: 'glass',
    vars: {
      '--bg': '#eef2f7',
      '--bg-image': 'radial-gradient(1000px 520px at 8% -8%, #cfe0ff 0%, transparent 58%), radial-gradient(820px 460px at 106% 108%, #ffd6e8 0%, transparent 55%)',
      '--surface': 'rgba(255,255,255,.55)',
      '--surface-sunk': 'rgba(0,0,0,.05)',
      '--surface-raised': 'rgba(255,255,255,0.64)',
      '--sh-dark': 'rgba(120,130,150,.22)',
      '--sh-light': 'rgba(255,255,255,.70)',
      '--text': '#2c3242',
      '--text-soft': '#404858',
      '--text-dim': '#5f6878',
      '--text-mute': '#7e889a',
      '--accent': '#3f74e0',
      '--env-color': '#1c9783',
      '--ok': '#1b9d4b',
      '--running': '#4987f5',
      '--warn': '#c07c09',
      '--danger': '#ef4444',
      '--border': 'rgba(255,255,255,.65)',
      '--blur': '16px',
      '--r-xl': '18px',
      '--r-lg': '14px',
      '--r-md': '11px',
      '--r-sm': '7px',
    },
  },
  {
    id: 'glass-aurora',
    name: '极光玻璃',
    desc: '强色彩渐变配毛玻璃 · 视觉冲击最强',
    base: 'dark',
    style: 'glass',
    vars: {
      '--bg': '#141024',
      '--bg-image': 'radial-gradient(900px 520px at 6% -6%, #1e4d8c 0%, transparent 55%), radial-gradient(760px 460px at 100% 6%, #7b2d7d 0%, transparent 52%), radial-gradient(880px 500px at 50% 118%, #0f5f5c 0%, transparent 58%)',
      '--surface': 'rgba(255,255,255,.09)',
      '--surface-sunk': 'rgba(0,0,0,.26)',
      '--surface-raised': 'rgba(255,255,255,0.18)',
      '--sh-dark': 'rgba(0,0,0,.40)',
      '--sh-light': 'rgba(255,255,255,.10)',
      '--text': '#f2eefc',
      '--text-soft': '#d9d3ed',
      '--text-dim': '#b3aad6',
      '--text-mute': '#7f77a8',
      '--accent': '#8ce0ff',
      '--env-color': '#ff9ad5',
      '--ok': '#22c55e',
      '--running': '#4c8dff',
      '--warn': '#f59e0b',
      '--danger': '#ef4444',
      '--border': 'rgba(255,255,255,.15)',
      '--blur': '18px',
      '--r-xl': '18px',
      '--r-lg': '14px',
      '--r-md': '11px',
      '--r-sm': '7px',
    },
  },

  /* ---------------- 默认 ---------------- */
  {
    id: 'agentflow-dark',
    name: 'Agent Flow 深色',
    desc: 'Linear / Vercel 风 · 扁平，靠明度差分层',
    base: 'dark',
    style: 'flat',
    vars: {
      /*
        这些值与 agent-flow 插件的原生层（--af-native-*）逐像素相同。
        插件在「跟随面板」模式下读取本主题的变量，于是：
            跟随 + Agent Flow 深色  ≡  原生模式
        改动这里任何一个值都会破坏这个等价性 —— 所以本主题刻意
        不参与「文本 / 点缀色对比度微调」，改色前请先想清楚。
      */
      '--bg': '#0f1115',
      '--surface': '#171a21',
      '--surface-sunk': '#12151c',
      '--surface-raised': '#222836',
      '--sh-dark': '#0b0d11',
      '--sh-light': '#13161b',
      '--text': '#e6e9ef',
      '--text-soft': '#c4cbd9',
      '--text-dim': '#8b93a7',
      '--text-mute': '#687285',
      '--accent': '#4c8dff',
      '--env-color': '#22c55e',
      '--ok': '#22c55e',
      '--running': '#4c8dff',
      '--warn': '#f59e0b',
      '--danger': '#ef4444',
      '--border': '#262b36',
      '--blur': '0px',
      '--r-xl': '12px',
      '--r-lg': '10px',
      '--r-md': '8px',
      '--r-sm': '5px',
    },
  },
];


/**
 * 浅色底专用色板。
 *
 * 同一组色值在深底浅底上的表现差异极大：#48e0c0（青）在深色底上
 * 对比度 10.5:1，放到浅色底 #e6e9ef 上只有 1.4:1 —— 基本看不见。
 * 所以浅色底统一压暗 42%，实测全部 ≥ 3.8:1。
 */
function darken(hex, amount) {
  const m = String(hex).match(/^#([0-9a-f]{6})$/i);
  if (!m) return hex;
  const h = m[1];
  const f = (v) => Math.max(0, Math.min(255, Math.round(v * (1 - amount))));
  return '#' + [0, 2, 4]
    .map((i) => f(parseInt(h.substr(i, 2), 16)).toString(16).padStart(2, '0'))
    .join('');
}

/** 强调色与环境色共用的候选色板 */
export const ACCENT_SWATCHES = [
  ['#5b8cff', '蓝'], ['#7aa2ff', '天蓝'], ['#48e0c0', '青'],
  ['#3ddc97', '薄荷'], ['#b48cff', '紫'], ['#ff2e97', '品红'],
  ['#ff8f5b', '橙'], ['#ffb454', '琥珀'], ['#ff6b8b', '粉'],
];

export const ACCENT_SWATCHES_LIGHT = ACCENT_SWATCHES.map(([c, l]) => [darken(c, 0.42), l]);

/** 按面板基调取对应色板：深色底用原色，浅色底用压暗版 */
export function swatchFor(base) {
  return base === 'light' ? ACCENT_SWATCHES_LIGHT : ACCENT_SWATCHES;
}

/**
 * 面板默认主题。
 *
 * 设为 Agent Flow 深色：它的变量值与 agent-flow 插件的原生层一致，
 * 因此未手动选过主题的用户打开插件时，观感与插件独立运行时完全相同。
 */
export const DEFAULT_THEME_ID = 'agentflow-dark';
